### ISSUE TITLE
[ISSUE] WingetUI 2.0.0 is detected as Wacatac.B!ml by Windows Defender

### ISSUE THREAD

**Issue by oXydus** [marticliment/WingetUI#1113]
Just installed the release of WingetUI 2.0.0 and Windows Defender has quarantined wingetui.exe as Wacatac.B!ml.

**Comment by marticliment** [comment]
I have submitted a false-positive form.

Please submit yours at https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by marticliment** [comment]
VirusTotal results: https://www.virustotal.com/gui/file/26fd4ab5aaf5d83b633566bc4ef3ec92e5d643ac49e3c5f73ad67fcc14f19296/behavior

**Comment by marticliment** [comment]
This should be fixed by now:

![image](https://github.com/marticliment/WingetUI/assets/53119851/8003b46f-5494-4c37-8970-3a71362db336)
![image](https://github.com/marticliment/WingetUI/assets/53119851/10f3d166-1431-4482-9312-92c73f9fddc7)
![image](https://github.com/marticliment/WingetUI/assets/53119851/839ffdf6-90f9-4223-aa34-8e95972513e3)
![image](https://github.com/marticliment/WingetUI/assets/53119851/958649f1-5807-4dc3-8b2a-7a74ba939c22)
![image](https://github.com/marticliment/WingetUI/assets/53119851/d9c7ea66-3804-4321-81c7-5e7290472ef7)

**Comment by furkanevran** [comment]
@marticliment Windows Defender just detected wingetui.exe as `Trojan:Win32/Sabsik.FL.B!ml`.

22:00 at UTC+3
![image](https://github.com/marticliment/WingetUI/assets/14177182/9dc7d48f-7fe6-4e05-b8d7-0265ab314dab)

**Comment by marticliment** [comment]
Try searching for updates, since you may not have the latest virus definitions on your system

**Comment by furkanevran** [comment]
Just updated the defender database (1.391.1664.0) and re-scanned the file and it's still the same, I also sent a false-positive report to the defender.

![image](https://github.com/marticliment/WingetUI/assets/14177182/474ae6f5-2ca7-49b3-83fd-c20c3c0b51bd)

**Comment by ngdio** [comment]
Still occured on definition version 1.391.1749.0. Also submitted as false positive but doesn't seem to be resolved

**Comment by strawbeard** [comment]
Resetting Defender via the command line (as  proposed [here](https://github.com/marticliment/WingetUI/issues/1116#issuecomment-1595721890)) **did'nt** help. Windows 10 22H2, WingetUI.Installer-2.0.1
